### ISSUE TITLE
Specify dependencies using pyproject.toml and lockfile

### ISSUE THREAD

**Issue by imbev** [nixietab/picodulce#1]
I suggest adding a pyproject.toml file so that dependencies are tracked.

Depending on the packaging tool that you use (Poetry, uv, etc.) I suggest that you also use a lockfile, whether poetry.lock, requirements.txt or another format.

These changes will ensure that the project can be run in different environments without Python dependency issues.

**Comment by nixietab** [comment]
requirements.txt added.
ill think to add poetry in the future, thanks
