### ISSUE TITLE
Laucher displays only cursor when launched

### ISSUE THREAD

**Issue by Scrub41h** [nixietab/picodulce#4]
After creating a venv, and running ``pip3 install -r requirements.txt``, I ran ``chmod +x picodulce.py`` and then ``./picodulce.py``.
It displayed a sort of plus sign shaped cursor, which would allow me to draw a square outline on my screen if clicked and dragged.
Nothing was displayed on the terminal until after I spammed ctrl+c, after which I got this:
```
(.venv) C:\home\scrub\Projects\picodulce> ./picodulce.py 
./picodulce.py: line 4: from: command not found
./picodulce.py: line 11: from: command not found
./picodulce.py: line 12: from: command not found
./picodulce.py: line 13: from: command not found
./picodulce.py: line 15: syntax error near unexpected token `level=logging.ERROR,'
./picodulce.py: line 15: `logging.basicConfig(level=logging.ERROR, format='%(asctime)s - %(levelname)s - %(message)s')'
```

**Comment by nixietab** [comment]
you should execute it with python instead. it isnt a binary, try with `python picodulce.py` or `python3 picodulce.py`
if you are on Windows there is a installer called [2hsu](https://github.com/nixietab/2hsu/releases/tag/release)
